### PR TITLE
Fix chest narration

### LINKED ISSUE #149: now chests are broken.
Hi, while fixing the shipping bin, you broke the chests.

### PR DESCRIPTION
**Pull request by Flameborn**
Add missing return statement which fixes chest narration. Closes #149.

### CODE REVIEW

File: stardew-access/Patches/MenuWithInventoryPatches/ItemGrabMenuPatch.cs [hunk 1]
```diff
@@ -106,11 +106,11 @@ private static bool NarrateHoveredButton(ItemGrabMenu __instance, int x, int y)
                         toSpeak = $"{toSpeak} Selected";
                     goto SayWithChecker;
                 }
+                return false;
             }
             else
```
Comment (khanshoaib3) [inline stardew-access/Patches/MenuWithInventoryPatches/ItemGrabMenuPatch.cs]: I think we can move `__instance.discreteColorPickerCC != null` to the for loop itself and make the previous one only else, lemme check if that works.

Comment (khanshoaib3) [reply stardew-access/Patches/MenuWithInventoryPatches/ItemGrabMenuPatch.cs]: Yup, making the last else if as else and having this condition in for loop fixes it, `__instance.discreteColorPickerCC != null && i < __instance.discreteColorPickerCC.Count`, will commit the changes.

**Review by khanshoaib3 — APPROVED** [review]
